services:
  - type: web
    name: django-portfolio
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio_project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
