# Generated by Django 4.2.7 on 2026-05-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_aboutme_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='resume',
            field=models.URLField(blank=True, help_text='Direct link to your resume (Google Drive, Dropbox, etc.)', null=True),
        ),
    ]
